### ISSUE TITLE
Can't install packages

### ISSUE THREAD

**Issue by kaelig** [fonzie/fonzie#1]
To reproduce: `fonzie install clear-floats`:

```
failed to fetch https://raw.github.com/clear-floats/master/component.json, got 404 "Not Found"
```

Looks like fonzie is trying to fetch the manifest at the wrong URL (should try to resolve `https://raw.github.com/fonzie/clear-floats/master/component.json` instead — with the name of the author in the url).

![Fonzie](http://stream1.gifsoup.com/view/100547/fonzie-o.gif)

**Comment by anthonyshort** [comment]
Interesting. Could you post your component.json file? If you create a component using fonzie init does it work for you?

**Comment by anthonyshort** [comment]
I hope we see a lot of fonzie gifs :facepunch:

**Comment by kaelig** [comment]
Awesome, after running `fonzie init` it works.

Here was the component.json file created when running `fonzie install clear-floats`:

```
{
  "dependencies": {
    "breakpoints": "*",
    "clear-floats": "*",
    "media-block": "*"
  }
}
```

To avoid this, the tool might want to warn the user he should run `fonzie init` when running anything else?

**Comment by anthonyshort** [comment]
It was probably because the remotes section wasn't set in your config. I might default that. It's really only there so you can install these packages with Component if you want.
