### ISSUE TITLE
Avoid creating empty file

### ISSUE THREAD

**Issue by MoOx** [fonzie/fonzie#11]
When I run build, it first create an empty file, then fill it with sassified styles.
The problem is, with stuff like livereload, it reload stylesheet once in my browser (with no styles) then reload again with styles if build is okay. Is it hard to avoid that empty, then fill with sass ?

**Comment by anthonyshort** [comment]
Hrrrmmmm that could be Sass. Ill take a look

**Comment by MoOx** [comment]
Hum it's a Sass issue... https://github.com/gruntjs/grunt-contrib-livereload/issues/12

**Comment by MoOx** [comment]
Fixed by https://github.com/nex3/sass/commit/a7bdf6126c32493f5a25b2cf958cc648026cf1e4 :)
