### ISSUE TITLE
Configuration variables

### ISSUE THREAD

**Issue by MoOx** [fonzie/fonzie#13]
What about adding a variables field into the json config à la Compass ?
Like this

``` js
{
    "variables": {
        "images": "./images" // can be used by ruby ?
        "http": {
            "images": "assets/img" // can be used for building url()
        }
}
```

**Comment by MoOx** [comment]
This can create a simple tmp sass file that embed this as "simple" sass variables ?

**Comment by MoOx** [comment]
And if `-r` option is enabled, this also create a ruby file containing this variables.

**Comment by anthonyshort** [comment]
One thing I really want to sort out are relative image urls so that packages can contain their own assets and easily reference them. This would be way more modular. You could keep everything together. I'm currently doing this at work and it works really well. That pretty much means you don't need settings for image paths.

**Comment by MoOx** [comment]
So the build process will be able to move required assets to a specific folder ? (eg: dist/images, dist/fonts...) There will be some configurable paths somewhere... ?

**Comment by anthonyshort** [comment]
Nope, it will know where the build directory is and where the components are, then it can write relative urls. That's the plan so far. 

If that doesn't work, then it will copy a set folder, say "assets" to the build directory as the name of the component. This is one area that sucks about CSS.

**Comment by anthonyshort** [comment]
Convention over configuration is what I'm going for.

**Comment by MoOx** [comment]
I don't like the idea about having "components" into my dist dir, but maybe I'm just afraid of "Idon'tknowwhatImafraidof"...
Be careful to don't be too opinionated with this kind of "convention". Tools like grunt show us how important is configuration :)

**Comment by anthonyshort** [comment]
The weird part is referencing those paths in the Sass. You'd be writing them as `url('my-module/foo/bar.png')` which won't make sense unless you are building things with Fonzie.

**Comment by anthonyshort** [comment]
This is pretty much handled by the new version with the "fonzie" section in bower.json
