### ISSUE TITLE
Output is invisible with Solarized theme

### ISSUE THREAD

**Issue by kevva** [fonzie/fonzie#14]
When using the Solarized Dark terminal theme, you can't see the majority of the output. It's caused by `\033[90m%s\033[m` on line https://github.com/fonzie/fonzie/blob/master/lib/utils.js#L29. The color code 90 produces a dark text that blends into the background on Solarized.

**Comment by anthonyshort** [comment]
Hrm, damn. Ill check that out. I might just avoid colours and keep it simple.

**Comment by kevva** [comment]
Yeah, this is a common problem with Solarized Dark. I'd just stick to the default text.

**Comment by anthonyshort** [comment]
This is fixed with the new version
