### ISSUE TITLE
Avoid confusion

### ISSUE THREAD

**Issue by kevva** [fonzie/fonzie#15]
Hey, while I think this is a fantastic project, I don't understand the `install` command. Why not encourage the use of package management tools like Bower or component instead of creating confusion by creating your own `install` command that does essentially the same thing.

I'd focus on the build part instead, which is what makes this project great.

**Comment by anthonyshort** [comment]
That's actually what I'm doing now. I'm switching the install to bower and focusing on making it super easy to just build projects with packages. Ill probably finish the move of everything soon.

**Comment by kevva** [comment]
:cake:

**Comment by anthonyshort** [comment]
Totally using bower now!
